- name: "Ensure /etc/bdii/gip exists"
  ansible.builtin.file:
    path: /etc/bdii/gip
    state: directory
    mode: "0755"

- name: "Write /etc/bdii/gip/site-urls.conf"
  ansible.builtin.template:
    src: site-urls.conf.j2
    dest: /etc/bdii/gip/site-urls.conf
    mode: "0644"

