- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart bdii
  ansible.builtin.systemd:
    name: bdii
    state: restarted
  when:
    - ansible_facts.service_mgr == "systemd"

